repos:
  - repo: local
    hooks:
      - id: ruff
        name: Ruff
        entry: poetry run ruff src
        pass_filenames: false
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: poetry run mypy
        args: ["src"]
        language: system
        pass_filenames: false
        types: [python]
