repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff Linter
        entry: poetry run ruff check
        args: ["src"]
        pass_filenames: false
        language: system
        types: [ python ]
      - id: ruff-format
        name: Ruff Formatter
        entry: poetry run ruff format
        args: [ "src" ]
        pass_filenames: false
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: poetry run mypy
        args: ["src"]
        language: system
        pass_filenames: false
        types: [python]
