repos:
  - repo: local
    hooks:
      - id: black
        name: Black
        entry: poetry run black
        args: ["src"]
        pass_filenames: false
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: isort
        name: Isort
        entry: poetry run isort
        pass_filenames: false
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: flake8
        name: Flake8
        entry: poetry run flake8
        pass_filenames: false
        language: system
        types: [ python ]
  - repo: local
    hooks:
      - id: mypy
        name: Mypy
        entry: poetry run mypy
        args: ["src"]
        language: system
        pass_filenames: false
        types: [python]
